package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/widget"
)

type OptKind string

const (
	KindBool  OptKind = "bool"
	KindInt   OptKind = "int"
	KindFloat OptKind = "float"
	KindText  OptKind = "text"
)

type Option struct {
	Key         string
	Label       string
	Kind        OptKind
	DefaultText string
}

func main() {
	a := app.New()
	w := a.NewWindow("S&box Blueberry Configurator")

	// Welcome
	welcome := widget.NewLabel("\t Welcome to the S&box Blueberry Configurator.")
	desc := widget.NewLabel("There you can create a cool graphics_config.vcfg for s&box! \n Leave the values ​​if you want potato graphics.")

	// Path
	entry := widget.NewEntry()
	entry.SetPlaceHolder("C:/Program Files (x86)/Steam/steamapps/common/sbox")
	entry.Resize(entry.MinSize())

	pathtext := widget.NewLabel("Path: ")

	button := widget.NewButton("Select folder", func() {
		dialog.ShowFolderOpen(func(uri fyne.ListableURI, err error) {
			if err != nil {
				log.Println(err)
				return
			}
			if uri != nil {
				entry.SetText(uri.Path())
				fmt.Println("Selected folder:", uri.Path())
			}
		}, w)
	})

	pathbox := container.NewBorder(nil, nil, pathtext, button, entry)

	opts := []Option{
		{"r_postprocess", "Post-processing", KindBool, "0"},
		{"r_bloom", "Bloom", KindBool, "0"},
		{"r_motionblur_scale", "Motion blur scale", KindFloat, "0"},
		{"r_filmgrain", "Film grain", KindBool, "0"},
		{"r_lensflare", "Lens flare", KindBool, "0"},
		{"r_depth_of_field", "Depth of field", KindBool, "0"},
		{"r_vignette", "Vignette", KindBool, "0"},

		{"r_shadows", "Shadows (on/off)", KindBool, "0"},
		{"r_shadow_quality", "Shadow quality", KindInt, "0"},
		{"r_shadow_max_resolution", "Shadow max resolution", KindInt, "256"},
		{"r_shadow_cascades", "Shadow cascades", KindInt, "0"},
		{"r_shadow_half_update_rate", "Shadow half update rate (opt)", KindBool, "1"},

		{"r_ssr", "Screen space reflections (SSR)", KindBool, "0"},
		{"r_ssr_quality", "SSR quality", KindInt, "0"},
		{"r_ssr_downsample_ratio", "SSR downsample ratio", KindInt, "3"},
		{"r_ao", "Ambient occlusion (AO)", KindBool, "0"},
		{"r_ao_quality", "AO quality", KindInt, "0"},

		{"r_draw_skybox", "Draw skybox", KindBool, "0"},
		{"r_3d_skybox_depth_prepass", "3D skybox depth prepass", KindBool, "0"},
		{"r_grass_quality", "Grass quality", KindInt, "0"},
		{"r_water_quality", "Water quality", KindInt, "0"},
		{"r_water_draw_reflection", "Water draw reflection", KindBool, "0"},
		{"r_water_draw_refraction", "Water draw refraction", KindBool, "0"},

		{"r_texture_pool_size", "Texture pool size (VRAM MB)", KindInt, "1024"},
		{"r_texture_lod_scale", "Texture LOD scale", KindFloat, "2.5"},
		{"r_texture_streaming", "Texture streaming", KindBool, "1"},
		{"r_texture_anisotropic_filtering", "Texture anisotropic filtering", KindInt, "0"},

		{"r_threaded_renderables", "Threaded renderables", KindBool, "1"},
		{"r_threaded_particles", "Threaded particles", KindBool, "1"},
		{"r_threaded_client_shadow_manager", "Threaded client shadow manager", KindBool, "1"},
		{"mat_queue_mode", "Material queue mode", KindInt, "2"},
		{"engine_no_focus_sleep", "No focus sleep (don't slow when unfocused)", KindBool, "0"},
		{"fps_max", "Max FPS", KindInt, "240"},
	}

	// Options
	controls := make(map[string]fyne.CanvasObject)

	var objs []fyne.CanvasObject
	for _, o := range opts {
		switch o.Kind {
		case KindBool:
			initialChecked := !(o.DefaultText == "0" || strings.EqualFold(o.DefaultText, "false"))
			ch := widget.NewCheck(o.Label, func(b bool) {
				_ = b
			})
			ch.SetChecked(initialChecked)
			controls[o.Key] = ch
			objs = append(objs, ch)
		default:
			e := widget.NewEntry()
			e.SetText(o.DefaultText)
			e.Validator = nil
			controls[o.Key] = e
			row := container.NewHBox(widget.NewLabel(o.Label), e)
			objs = append(objs, row)
		}
	}

	getConfigPath := func() string {
		dir := strings.TrimSpace(entry.Text)
		if dir == "" {
			pwd, err := os.Getwd()
			if err == nil {
				dir = pwd
			} else {
				dir = "."
			}
		}
		return filepath.Join(dir, "core", "cfg", "graphics_config.vcfg")
	}

	saveBtn := widget.NewButton("Save to vcfg", func() {
		fp := getConfigPath()
		f, err := os.Create(fp)
		if err != nil {
			dialog.ShowError(err, w)
			return
		}
		defer f.Close()

		fmt.Fprintln(f, "// s&box graphics config | Generated by S&box Blueberry Configurator")
		fmt.Fprintln(f)

		for _, o := range opts {
			var valStr string
			co := controls[o.Key]
			switch w := co.(type) {
			case *widget.Check:
				if w.Checked {
					valStr = "1"
				} else {
					valStr = "0"
				}
			case *widget.Entry:
				valStr = strings.TrimSpace(w.Text)
				if valStr == "" {
					valStr = o.DefaultText
				}
			default:
				valStr = o.DefaultText
			}
			fmt.Fprintf(f, "%s %s\n", o.Key, valStr)
		}

		dialog.ShowInformation("Saved", "Saved to "+fp, w)
	})

	scroll := container.NewVScroll(container.NewVBox(objs...))
	scroll.SetMinSize(fyne.NewSize(520, 380))

	top := container.NewVBox(welcome, desc, pathbox)
	bottom := container.NewMax(saveBtn)

	content := container.NewBorder(top, bottom, nil, nil, scroll)

	w.SetContent(content)

	w.Resize(fyne.NewSize(1000, 500))
	w.ShowAndRun()
}
